// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KontaktformularTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void kontaktformular() {
    driver.get("https://automationexercise.com/");
    driver.manage().window().setSize(new Dimension(1936, 1066));
    assertThat(driver.getTitle(), is("Automation Exercise"));
    driver.findElement(By.linkText("Contact us")).click();
    assertThat(driver.findElement(By.cssSelector(".title:nth-child(2)")).getText(), is("GET IN TOUCH"));
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("ramadbes");
    driver.findElement(By.name("email")).sendKeys("ramadbes@students.zhaw.ch");
    driver.findElement(By.name("subject")).sendKeys("DevOps Lernjournal");
    driver.findElement(By.id("message")).sendKeys("Das ist eine Testnachricht für das Lernjournal durch ramadbes im Frühlingssemester 2024.");
    driver.findElement(By.name("submit")).click();
    assertThat(driver.switchTo().alert().getText(), is("Press OK to proceed!"));
    driver.switchTo().alert().accept();
    assertThat(driver.findElement(By.cssSelector(".status")).getText(), is("Success! Your details have been submitted successfully."));
  }
}
